Add initial views for field enrollment and field practices
mstenta/farm_pcsc pull request #2
Opened 2024-03-28 22:20 UTC by paul121

This requires the changes from https://github.com/farmOS/farmOS/pull/818 so that `plan_record` entity works in views.

Table of field enrollments at `/plan/%plan/fields`:
![view-field-enrollment](https://github.com/mstenta/farm_pcsc/assets/3116995/b0f2863f-a9f3-47de-bc44-7693b48fb935)

A grid display of field practices at `/plan/%plan/fields/%asset/practices`:

I chose to use the grid display instead of a table because I believe for OpenTEAM ACTION each field will only be implementing a few practices, likely < 5? Having a table means we need to choose which columns to display which would be different for each practice bundle. Using a grid display + "Rendered Entity in view mode" makes it much easier to render (with some simple styling, TBD) a "card" with data specific to each practice. We could allow each bundle (using bundle classes) to define a method/logic for rendering an "overview/preview" view mode to tailor this information a bit more. At the top of each card I added the label of the practice bundle and a simple `Edit` link. Once created it is pretty easy to edit these practice bundles! 

![view-field-practices](https://github.com/mstenta/farm_pcsc/assets/3116995/7b20870b-eaae-4975-9487-45f5fba04a34)

2024-03-29 10:55 UTC, mstenta requested changes
@paul121 Can we put in a temporary commit that safely makes the same changes as https://github.com/farmOS/farmOS/pull/818, but can be reverted once that's in core? That would make it easier to deploy this to the testing site that is running 3.1.2 right now.

2024-04-01 20:50 UTC, paul121 commented
> @paul121 Can we put in a temporary commit that safely makes the same changes as [farmOS/farmOS#818](https://github.com/farmOS/farmOS/pull/818), but can be reverted once that's in core? That would make it easier to deploy this to the testing site that is running 3.1.2 right now.

Unfortunately I don't think we can :-/ We can alter the `views_data` handler but there isn't a way to alter the entity type's data table. There is only a getter method available on the `EntityTypeInterface` which is the interface for objects passed through to `hook_entity_type_build` and `hook_entity_type_alter`. This makes sense, normally it would not be a good idea to alter the entity type data table.

2024-04-01 22:40 UTC, paul121 commented
Aha! We can do `$entity_types['plan_record']->set('data_table', NULL)`

2024-04-02 10:21 UTC, mstenta approved these changes

2024-04-02 10:22 UTC, merged